# Generated by Django 5.1.3 on 2024-11-10 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Abbreviations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Abbreviationsloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
            ],
            options={
                'db_table': 'AbbreviationsLoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BacBiologicalactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'BAC_BiologicalActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BacPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.TextField()),
            ],
            options={
                'db_table': 'BAC_Plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biologicalactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'BiologicalActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biologicalactivitygroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'BiologicalActivityGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biologicallyactivecompounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('compounds_group_text', models.TextField()),
                ('note', models.TextField()),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
                ('comment', models.TextField()),
                ('rus_alt', models.TextField(blank=True, null=True)),
                ('biological_activity_extra', models.TextField()),
            ],
            options={
                'db_table': 'BiologicallyActiveCompounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemicalcompounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ChemicalCompounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemicalcompoundsgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
            ],
            options={
                'db_table': 'ChemicalCompoundsGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
            ],
            options={
                'db_table': 'Families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('long_title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
            ],
            options={
                'db_table': 'Parts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rus', models.TextField()),
                ('eng', models.TextField()),
            ],
            options={
                'db_table': 'Plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantsNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Plants_Names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantsOthernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Plants_OtherNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantsParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Plants_Parts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spreading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Spreading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Abbreviationsreg',
            fields=[
                ('abbreviation', models.OneToOneField(db_column='abbreviation', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='herbalist.abbreviations')),
                ('transcript', models.TextField()),
            ],
            options={
                'db_table': 'AbbreviationsReg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemicalcompoundsdistribution',
            fields=[
                ('activity', models.OneToOneField(db_column='activity', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='herbalist.biologicalactivitygroups')),
            ],
            options={
                'db_table': 'ChemicalCompoundsDistribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixtures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Mixtures',
            },
        ),
        migrations.CreateModel(
            name='MixtureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('selected', models.BooleanField(default=True)),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalist.mixtures')),
            ],
            options={
                'db_table': 'MixtureList',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'EN'), ('ru', 'RU')], default='en', max_length=2)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ai_usage', models.IntegerField(default=0)),
                ('page_size', models.IntegerField(default=12)),
                ('page_buttons', models.IntegerField(default=4)),
                ('model_name', models.CharField(default='', max_length=255)),
                ('models_date', models.DateField(blank=True, null=True)),
                ('model_temp', models.FloatField(blank=True, null=True)),
                ('model_top_p', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
